name: watch for flutter updates

on:
  # Check every 15 minutes
  schedule:    
    - cron: "*/15 * * * *"

  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

  workflow_dispatch:

jobs:
  check-update:
    name: 'Check for Flutter Updates'
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        channel: [ stable, beta, master ]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: flutter/${{ matrix.channel }}
          # We need to use a custom token here to be able to push commits.
          token: ${{ secrets.ENGINE_ROLL_TOKEN }}

      - name: Find current flutter ${{ matrix.channel }} commit and semver
        id: resolve
        env:
          GIT_BASECMD: "git -c gc.autoDetach=false -c core.pager=cat -c safe.bareRepository=all"
          FLUTTER_REPO: "https://github.com/flutter/flutter.git"
        run: |
          # Get the current commit of refs/heads/stable for the flutter repo.
          HASH=$($GIT_BASECMD ls-remote --exit-code --branches "$FLUTTER_REPO" "${{ matrix.channel }}" | cut -f1)
          
          # Try to find a semver for this hash.

          # Get all (full-qualified) tags that point to the engine commit
          # e.g. refs/tags/2.10.0-0.0.pre.0
          REFS=$($GIT_BASECMD ls-remote --tags "$FLUTTER_REPO" "$HASH" | cut -f2)

          # Extract the tag names from the full-qualified refs
          # e.g. 2.10.0-0.0.pre.0
          TAGS=$(echo "$REFS" | cut -d/ -f3 | sort -V)
          
          # Extract the first tag
          FIRST_TAG=$(head -n1 <<< "$TAGS")
          
          echo "semver=$FIRST_TAG" >> $GITHUB_OUTPUT

          # Put it into "flutter.version".
          echo "$HASH" > "flutter.version"

      - name: Check if flutter version changed 
        id: check-roll
        run: |
          git status
          if git diff-index --quiet HEAD -- flutter.version; then
            echo "No changes"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Delta"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Log
        run: |
          echo '*** Flutter version changed? ***'
          echo steps.check-roll.outputs.changed: ${{ steps.check-roll.outputs.changed }}

      - name: Commit new flutter version
        # the if is not really necessary since the add-and-commit action won't push empty commits, but this way it feels safer
        # (it won't even push the tag if we have an empty commit)
        if: ${{ steps.check-roll.outputs.changed == 'true' }}
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Roll Flutter (${{ matrix.channel }})'
          add: 'flutter.version'
          tag: flutter/${{matrix.channel}}/${{ steps.resolve.outputs.semver || steps.resolve.outputs.hash }} --force
          tag_push: '--force'
